### ISSUE TITLE
Improve error text

### ISSUE THREAD

**Issue by maxrothman** [collegevine/confcrypt#30]
It appears that confcrypt currently creates text of errors by simply `show`ing the error, resulting in messages like this:
```
FormatParseError "1:3:\n  |\n1 | %x\n  |   ^\nUnrecognized variable x\n"
```
This is what you get if you pass a bad template to `read --format`, I suspect others are worse since the text in the error is created via `show` rather than `errorBundlePretty`.

**Comment by ChrisCoffey** [comment]
Well, you're looking only at the parser, but this is a good find.

**Comment by ChrisCoffey** [comment]
Fixed via https://github.com/collegevine/confcrypt/commit/65f5d32c25b00a86af188a426f3f7887f30b2776
